### ISSUE TITLE
"Save As..." is still greyed out 

### ISSUE THREAD

**Issue by GeorgesGraire** [eishiya/tiled-expand-autotile#2]
I'm sorry to report that the "Save As..." button is still not clickable.

![image](https://github.com/eishiya/tiled-expand-autotile/assets/82153698/4b7eefa1-a7eb-4c68-b201-4be736bada9e)

**Comment by eishiya** [comment]
Please don't open duplicate issues, your comment on the previous issue is sufficient. We can reopen that issue if need be.
